### ISSUE TITLE
Project Moved?

### ISSUE THREAD

**Issue by backlands** [fithwum/teamspeak-server#1]
@fithwum I was just reviewing my docker containers on unRAID and saw that this image was showing as unavailable. After some searching it looks like the old source at https://hub.docker.com/r/fithwum/teamspeak-alpine/ has been moved to https://hub.docker.com/r/fithwum/teamspeak-server/.

Can you confirm that this is just a migration of the images with no other changes, just want to ask since the old version has been removed entirely I can't compare contents or image hashes. The image hash I have locally doesn't match so doing some due diligence on my end here before changing registry references.

**Comment by fithwum** [comment]
Yes it is just a migration nothing else changed, just take note of the new tags that i have added
